module.exports={
    PRODUCT_COLLECTION:'products',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    ORDER_COLLECTION:'orders',
    BANNER_COLLECTION:'banner'
}